### ISSUE TITLE
Challenges in testing scalable MF/TF methods

### ISSUE THREAD

**Issue by postech-data-intelligence-lab** [postech-di-lab/METIS#8]
We have the scalable MF (i.e., OCAM) and TF (i.e., FTcom) components in the model-layer directory, but I found that they are too difficult to be executed for testing purposes. I think we need to add several toy-example matrices (or tensors) to make it possible run the components.

**Comment by donalee** [comment]
Okay, I will add some toy-example datasets for testing those modules.
